//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class personne
    {
        public int ID_PERSONNE { get; set; }
        public int ID_USER { get; set; }
        public string NOM_PERSONNE { get; set; }
        public string PRENOM_PERSONNE { get; set; }
        public string MAIL { get; set; }
        public string PATIENT_MEDECIN { get; set; }
    }
}
